onerr {resume}
add list -bin /test_bench/clk
add list -hex /test_bench/DUT/the_cpu_0/d_irq
add list -hex /test_bench/DUT/the_cpu_0/d_waitrequest
add list -hex /test_bench/DUT/the_cpu_0/d_address
add list -hex /test_bench/DUT/the_cpu_0/d_byteenable
add list -hex /test_bench/DUT/the_cpu_0/d_read
add list -hex /test_bench/DUT/the_cpu_0/d_readdata
add list -hex /test_bench/DUT/the_cpu_0/d_write
add list -hex /test_bench/DUT/the_cpu_0/d_writedata
add list -hex /test_bench/DUT/the_cpu_0/i_waitrequest
add list -hex /test_bench/DUT/the_cpu_0/i_address
add list -hex /test_bench/DUT/the_cpu_0/i_read
add list -hex /test_bench/DUT/the_cpu_0/i_readdata
add list -hex /test_bench/DUT/the_cpu_0/clk
add list -hex /test_bench/DUT/the_cpu_0/reset_n
add list -hex /test_bench/DUT/the_cpu_0/F_pcb_nxt
add list -hex /test_bench/DUT/the_cpu_0/F_pcb
add list -asc /test_bench/DUT/the_cpu_0/F_vinst
add list -asc /test_bench/DUT/the_cpu_0/D_vinst
add list -asc /test_bench/DUT/the_cpu_0/R_vinst
add list -asc /test_bench/DUT/the_cpu_0/E_vinst
add list -asc /test_bench/DUT/the_cpu_0/W_vinst
add list -hex /test_bench/DUT/the_cpu_0/F_valid
add list -hex /test_bench/DUT/the_cpu_0/D_valid
add list -hex /test_bench/DUT/the_cpu_0/R_valid
add list -hex /test_bench/DUT/the_cpu_0/E_valid
add list -hex /test_bench/DUT/the_cpu_0/W_valid
add list -hex /test_bench/DUT/the_cpu_0/D_wr_dst_reg
add list -hex /test_bench/DUT/the_cpu_0/D_dst_regnum
add list -hex /test_bench/DUT/the_cpu_0/W_wr_data
add list -hex /test_bench/DUT/the_cpu_0/F_iw
add list -hex /test_bench/DUT/the_cpu_0/D_iw
add list -hex /test_bench/DUT/the_cpu_0/hbreak_req
add list -hex /test_bench/DUT/the_cpu_0/oci_hbreak_req
add list -hex /test_bench/DUT/the_cpu_0/hbreak_enabled
add list -hex /test_bench/DUT/the_cpu_0/wait_for_one_post_bret_inst
add list -hex /test_bench/DUT/the_jtag_uart_0/av_address
add list -bin /test_bench/DUT/the_jtag_uart_0/av_chipselect
add list -bin /test_bench/DUT/the_jtag_uart_0/av_irq
add list -bin /test_bench/DUT/the_jtag_uart_0/av_read_n
add list -hex /test_bench/DUT/the_jtag_uart_0/av_readdata
add list -bin /test_bench/DUT/the_jtag_uart_0/av_waitrequest
add list -bin /test_bench/DUT/the_jtag_uart_0/av_write_n
add list -hex /test_bench/DUT/the_jtag_uart_0/av_writedata
add list -bin /test_bench/DUT/the_jtag_uart_0/dataavailable
add list -bin /test_bench/DUT/the_jtag_uart_0/readyfordata
add list -bin /test_bench/DUT/the_onchip_memory2_0/chipselect
add list -bin /test_bench/DUT/the_onchip_memory2_0/write
add list -hex /test_bench/DUT/the_onchip_memory2_0/address
add list -bin /test_bench/DUT/the_onchip_memory2_0/byteenable
add list -hex /test_bench/DUT/the_onchip_memory2_0/readdata
add list -hex /test_bench/DUT/the_onchip_memory2_0/writedata
configure list -usestrobe 0
configure list -strobestart {0 ps} -strobeperiod {0 ps}
configure list -delta none
configure list -usegating 1
configure list -gateexpr { /test_bench/clk'rising }